version: '3'

services:
  sources:
    image: postgres:latest
    container_name: sources
    restart: always
    environment:
      - POSTGRES_DB=${SRC_POSTGRES_DB}
      - POSTGRES_USER=${SRC_POSTGRES_USER}
      - POSTGRES_PASSWORD=${SRC_POSTGRES_PASSWORD}
    ports:
      - ${SRC_POSTGRES_PORT}:5432
    volumes:
      - ./helper/source_init:/docker-entrypoint-initdb.d
      - source-volume:/var/lib/postgresql/data

  stg:
    image: postgres:latest
    container_name: stg
    restart: always
    environment:
      - POSTGRES_DB=${STG_POSTGRES_DB}
      - POSTGRES_USER=${STG_POSTGRES_USER}
      - POSTGRES_PASSWORD=${STG_POSTGRES_PASSWORD}
    ports:
      - ${STG_POSTGRES_PORT}:5432
    volumes:
      - ./helper/stg_init:/docker-entrypoint-initdb.d
      - stg-volume:/var/lib/postgresql/data

  dwh:
    image: postgres:latest
    container_name: dwh
    restart: always
    environment:
      - POSTGRES_DB=${DWH_POSTGRES_DB}
      - POSTGRES_USER=${DWH_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DWH_POSTGRES_PASSWORD}
    ports:
      - ${DWH_POSTGRES_PORT}:5432
    volumes:
      - dwh-volume:/var/lib/postgresql/data
      - ./helper/dwh_init/:/docker-entrypoint-initdb.d

  log:
    image: postgres:latest
    container_name: log
    restart: always
    environment:
      - POSTGRES_DB=${LOG_POSTGRES_DB}
      - POSTGRES_USER=${LOG_POSTGRES_USER}
      - POSTGRES_PASSWORD=${LOG_POSTGRES_PASSWORD}
    ports:
      - ${LOG_POSTGRES_PORT}:5432
    volumes:
      - ./helper/log_init:/docker-entrypoint-initdb.d
      - log-volume:/var/lib/postgresql/data

volumes:
  source-volume:
  dwh-volume:
  stg-volume:
  log-volume: